version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: nuget restore
build:
  publish_wap: true
  verbosity: normal
build_script:
- ps: MSBuild.exe "/p:Configuration=Release" "/p:Platform=Any CPU" .\OpenCI.sln
artifacts:
- path: OpenCI.API.Rest\bin\WebDeploy\OpenCI.API.Rest.zip
  name: OpenCI.API.Rest
- path: OpenCI.EmailTemplateViewer.Service\bin\Release\PublishOutput
  name: OpenCI.EmailTemplateViewer.Service
deploy:
- provider: Environment
  name: scottrangerio